version: "3"
services:
  app:
    build: ./docker
    ports:
      - 8080:80
    restart: always
    volumes:
      - .:/var/www/html
    env_file: .env
    # environment:
    #   - "APACHE_DOCUMENT_ROOT=/var/www/html/public"
    #   - "sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf"
    #   - "sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf"  
    links:
      - mysql
  mysql:
    image: mysql:5.7.28
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33062:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=study_php
